redisio:
  restart: always
  image: redis:latest
postgresql:
  restart: always
  image: postgres:latest
multistreamer:
  restart: always
  image: jprjr/multistreamer:12.3.0-1
  links:
   - redisio
   - postgresql

